<a href="https://colab.research.google.com/github/LinoMendes/AprendendoFlutter/blob/main/CompracaoTexto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Script para comparação entre dois textos

In [1]:
#Importação
import numpy as np
import sklearn

## Inicio do processo de comparação


*   Primeiro vamos selecionar o texto que vamos usar como base "texto_base" e o texto que é nosso objeto de comparação "texto_a_ser_comparado";
*   Depois vamos fazer a "toclização" das palavras que compõe os textos.



In [15]:
from sklearn.feature_extraction.text import CountVectorizer

texto_a_ser_comparado = 'Suponha que esse seja o texto que desejo comparar'
texto_base = 'Suponha que esse seja o texto principal'

#Número de n_gramas
n=1

#Instância o contador de n_gramas
counts = CountVectorizer(analyzer ='word', ngram_range=(n,n))

#Criar uma matriz de contagem de n_grama para os dois textos
n_grams = counts.fit_transform([texto_a_ser_comparado, texto_base])

#Cria dicionário de n_gramas
vocab2int = counts.fit([texto_a_ser_comparado, texto_base]).vocabulary_

n_grams_array = n_grams.toarray()

print('Vetor de n_gramas: \n', n_grams_array)
print('Dicionário de n-gramas: \n', vocab2int)

Vetor de n_gramas: 
 [[1 1 1 0 2 1 1 1]
 [0 0 1 1 1 1 1 1]]
Dicionário de n-gramas: 
 {'suponha': 6, 'que': 4, 'esse': 2, 'seja': 5, 'texto': 7, 'desejo': 1, 'comparar': 0, 'principal': 3}


## Agora vamos utilizar o *containment* para comparar a similaridade entre os textos. Valendo-se entre a interseção entre eles.

In [16]:
# Vamos fazer determinar as interseções entre o texto de comparação e o texto base
intersecao = np.amin(n_grams_array, axis=0)
intersecao

array([0, 0, 1, 0, 1, 1, 1, 1])

In [17]:
# Vamos somar o número de intersecções entre os textos
intersecao_contagem = np.sum(intersecao)
intersecao_contagem

5

In [24]:
#Agora temso que normalizar os nossos dados
index = 0
diferenca = np.sum(n_grams_array[index])
diferenca


8

In [25]:
valor_normalizado = intersecao_contagem/diferenca
valor_normalizado

0.625

In [27]:
#tranformando em porcentagem
compatibilidade = valor_normalizado*100
print(f'A compatibilidade entre os dois textos é de: {compatibilidade}% ')

A compatibilidade entre os dois textos é de: 62.5% 
